apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../_envcommon
images:
  - name: 020124618381.dkr.ecr.us-west-2.amazonaws.com/nginx
    newTag: v1.48.0
